Add `debugError` dif tests
FerretDB/dance pull request #241
Opened 2022-11-16 13:29 UTC by noisersup

2022-11-18 07:53 UTC, rumyantseva commented on tests/diff/debug_error_test.go
> +	}{
Nice catch!

2022-11-18 07:54 UTC, rumyantseva requested changes
As @chilagrow mentioned, the case with `panic` is missing. The rest looks good to me!

2022-11-18 07:57 UTC, rumyantseva commented on tests/diff/debug_error_test.go
> +	} {
Maybe also one more case for empty input:

```go
input: ""
```

2022-11-18 09:24 UTC, w84thesun reviewed
LGTM, except for those mentioned cases.

2022-11-18 18:50 UTC, noisersup commented on tests/diff/debug_error_test.go
> +	}{
done

2022-11-20 17:43 UTC, rumyantseva approved these changes
LGTM

2022-11-21 01:54 UTC, chilagrow approved these changes

2022-11-21 01:55 UTC, chilagrow commented on tests/diff/debug_error_test.go
> +	}{
Thanks for the detailed comment :pray:

2022-11-21 09:06 UTC, w84thesun approved these changes

2022-11-21 09:07 UTC, merged