Add test for sort aggregation
FerretDB/dance pull request #84
Opened 2022-03-22 08:50 UTC by w84thesun

2022-03-22 10:47 UTC, w84thesun commented
I've checked errors. It seems that they are not related to changed code.

2022-03-22 11:59 UTC, AlekSi commented on tests/ferret/aggregation_test.go
> +			if tc.name == "" {
I think we better do `require.NotEmpty(t, tc.name)` to avoid mutating test cases

2022-03-23 06:14 UTC, seeforschauer requested changes
there are conflicts to resolve.

2022-03-23 06:14 UTC, seeforschauer commented on tests/ferret/aggregation_test.go
> +						if k == "_id" {
here you can remove complexity

2022-03-23 06:14 UTC, seeforschauer commented on tests/ferret/aggregation_test.go
> +				sort: bson.D{{"borough", int32(1)}, {"name", int32(1)}},
what the behavior will be if put negative value? 
what if put a string value? error?

2022-03-23 08:25 UTC, w84thesun commented on tests/ferret/aggregation_test.go
> +						if k == "_id" {
fixed

2022-03-23 09:15 UTC, seeforschauer submitted a review, later dismissed

2022-03-31 06:07 UTC, AlekSi requested changes
Tests fail

2022-04-01 12:44 UTC, AlekSi commented
I will close that one as we will add proper tests at #423.

2022-04-01 12:44 UTC, closed without merging